### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by njoguamos** [vmutius/EilingerV6#1]
Referring to this tweet: https://twitter.com/PovilasKorop/status/1632428750410244103?s=20

I can spare 30 minutes to review this code one-on-one via google meet or zoom.

Let me know if you are available.

**Comment by vmutius** [comment]
This is awesome. Thanks a lot
I don't know which timezone you are in. It is now nearly 8 o'clock in the evening in my timezone (CET).
Will be available for the next 2 or 3 hours or tomorrow in the late morning or in the evening again.

**Comment by njoguamos** [comment]
I am available now. https://meet.google.com/ewn-edmc-tgx?authuser=0
