### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by mnurullahsaglam** [vmutius/EilingerV6#3]
Hello, referring to Povilas Korop's tweet (https://twitter.com/PovilasKorop/status/1632428750410244103), and after this (https://github.com/vmutius/EilingerV6/issues/1) issue, I'd like to suggest more code review.

I have reviewed your repository committed some improvements. Please let me know if they are useful.

**Comment by vmutius** [comment]
Thanks a lot. I got some ideas from the first review and need to make them all happen.
Really appreciate your time.
